name: Publish Package to npmjs
on:
  release:
    types: [created]
  workflow_run:
    workflows: ["pauljs Version Control and Release Notes"]
    types:
      - completed
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'release' }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
      
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
      
      - name: Verify npm token
        run: |
          if [ -z "$NODE_AUTH_TOKEN" ]; then
            echo "Error: NPM_TOKEN is not set"
            exit 1
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Publish to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Log publish status
        run: |
          echo "Package published successfully"
          echo "Version: $(node -p "require('./package.json').version")"
          echo "Name: $(node -p "require('./package.json').name")" 