name: pauljs Version Control and Release Notes

on:
  push:
    branches: [ main ]

jobs:
  version-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Setup Git User
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git clean -fd
          git reset --hard HEAD
      
      - name: Analyze Changes
        id: analyze-changes
        run: |
          COMMITS=$(git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"%s")
          if echo "$COMMITS" | grep -q "^feat\|\\[feature\\]"; then
            echo "change=minor" >> $GITHUB_OUTPUT
          elif echo "$COMMITS" | grep -q "^fix:\|\\[bug\\]"; then
            echo "change=patch" >> $GITHUB_OUTPUT
          else
            echo "change=none" >> $GITHUB_OUTPUT
          fi

      - name: Determine Version Type
        id: version-type
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          if [[ "$CURRENT_VERSION" == 1.* ]]; then
            echo "type=alpha" >> $GITHUB_OUTPUT
            echo "tag=wormhole" >> $GITHUB_OUTPUT
          elif [[ "$CURRENT_VERSION" == 2.* ]]; then
            echo "type=beta" >> $GITHUB_OUTPUT
            echo "tag=event-horizon" >> $GITHUB_OUTPUT
          elif [[ "$CURRENT_VERSION" == 3.* ]]; then
            echo "type=release" >> $GITHUB_OUTPUT
            echo "tag=neutron" >> $GITHUB_OUTPUT
          else
            echo "type=release" >> $GITHUB_OUTPUT
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi

      - name: Generate Version
        id: generate-version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          if [[ "${{ steps.version-type.outputs.type }}" == "alpha" ]]; then
            if [[ "${{ steps.analyze-changes.outputs.change }}" == "minor" ]]; then
              NEW_VERSION=$(npx semver $CURRENT_VERSION -i minor)
              NEW_VERSION=$(npx semver $NEW_VERSION -i prerelease --preid alpha)
            elif [[ "${{ steps.analyze-changes.outputs.change }}" == "patch" ]]; then
              NEW_VERSION=$(npx semver $CURRENT_VERSION -i patch)
              NEW_VERSION=$(npx semver $NEW_VERSION -i prerelease --preid alpha)
            else
              NEW_VERSION=$(npx semver $CURRENT_VERSION -i prerelease --preid alpha)
            fi
          elif [[ "${{ steps.version-type.outputs.type }}" == "beta" ]]; then
            if [[ "${{ steps.analyze-changes.outputs.change }}" == "minor" ]]; then
              NEW_VERSION=$(npx semver $CURRENT_VERSION -i minor)
              NEW_VERSION=$(npx semver $NEW_VERSION -i prerelease --preid beta)
            elif [[ "${{ steps.analyze-changes.outputs.change }}" == "patch" ]]; then
              NEW_VERSION=$(npx semver $CURRENT_VERSION -i patch)
              NEW_VERSION=$(npx semver $NEW_VERSION -i prerelease --preid beta)
            else
              NEW_VERSION=$(npx semver $CURRENT_VERSION -i prerelease --preid beta)
            fi
          else
            if [[ "${{ steps.analyze-changes.outputs.change }}" == "minor" ]]; then
              NEW_VERSION=$(npx semver $CURRENT_VERSION -i minor)
            else
              NEW_VERSION=$(npx semver $CURRENT_VERSION -i patch)
            fi
          fi
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Clean Working Directory
        run: |
          git clean -fd
          git reset --hard HEAD
          
      - name: Update Version
        run: |
          npm version ${{ steps.generate-version.outputs.version }} -m "ci: bump version to %s [${{ steps.version-type.outputs.tag }}]" --no-git-tag-version
          git add package.json package-lock.json
          git commit -m "ci: bump version to ${{ steps.generate-version.outputs.version }} [${{ steps.version-type.outputs.tag }}]"
          git tag -a "v${{ steps.generate-version.outputs.version }}" -m "Version ${{ steps.generate-version.outputs.version }} [${{ steps.version-type.outputs.tag }}]"
      
      - name: Generate Release Notes
        run: |
          echo "Generating changelog..."
          node scripts/version-manager.js
          
          if [ -f CHANGELOG.md ]; then
            echo "Changelog content:"
            cat CHANGELOG.md
          else
            echo "Error: CHANGELOG.md was not generated!"
            exit 1
          fi
      
      - name: Commit Changes
        run: |
          echo "Staging changes..."
          git add package.json package-lock.json CHANGELOG.md
          
          echo "Git status:"
          git status
          
          echo "Committing changes..."
          git commit -m "release: version ${{ steps.generate-version.outputs.version }} [${{ steps.version-type.outputs.tag }}]" || echo "No changes to commit"
      
      - name: Push Changes
        run: |
          echo "Pushing changes to remote..."
          remote_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push "${remote_repo}" HEAD:main
          echo "Changes pushed successfully"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.generate-version.outputs.version }}
          name: Release v${{ steps.generate-version.outputs.version }} [${{ steps.version-type.outputs.tag }}]
          body_path: CHANGELOG.md
          draft: false
          prerelease: ${{ steps.version-type.outputs.type != 'release' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 